### ISSUE TITLE
matcaffe 

### ISSUE THREAD

**Issue by bighb69738** [twhui/MSG-Net#3]
could u teach me how to fix this error?
it's my email : bighb69738@gmail.com

https://imgur.com/mQCp5e4
https://imgur.com/tBT38gK

**Comment by twhui** [comment]
@bighb69738 Did you turn on matcaffe flag in your Makefile.config before you compile Caffe?

**Comment by bighb69738** [comment]
Hi,i have fixed the error. Because MSGNet.m  code gpu_id = 7 ,but i just have one gpu so my default value is '0'.
Thanks for your reply.
