### ISSUE TITLE
how to excluded patches without depth information

### ISSUE THREAD

**Issue by 980380446** [twhui/MSG-Net#4]
in your paper, you excluded patches without depth information due to occlusion, how to realize this?
thank you.

**Comment by twhui** [comment]
This is very simple. Crop and save a depth patch if the patch is not occluded.

**Comment by 980380446** [comment]
what i think is if a patches got any pixels of zero, the patch is occluded?

**Comment by twhui** [comment]
An occluded patch means it contains at least a single occluded pixel. Indeed, same definition as yours.

**Comment by 980380446** [comment]
thank you

**Comment by 980380446** [comment]
能用中文吗？想再问个问题，不知道怎么用英语

**Comment by twhui** [comment]
Sure

**Comment by 980380446** [comment]
按照你们论文里的方法将训练集裁剪成小图像块，我去掉了有0的图像块，但是还有很多表面均匀、没有明显边缘的图像块，请问你们有将这部分去掉吗？如何去掉的？

**Comment by twhui** [comment]
You can refer to this file MSG-Net/MSGNet-release/util/gen_train_data_x2.m

**Comment by 980380446** [comment]
thank you

**Comment by YNX940214** [comment]
@980380446 Hi, did you successfully re-implement  the result?

**Comment by 980380446** [comment]
just follow author's instruction
