### ISSUE TITLE
MATLAB Crashing on Ubuntu System

### ISSUE THREAD

**Issue by rustycandlewick** [twhui/MSG-Net#9]
Hi,

I am currently trying to run the MSGNet.m file. However, after saying 'Run CNN...' the code continually crashes (no crash message) and then restarts in terminal again. Would you know why this is the case? I am running on CPU mode.

**Comment by twhui** [comment]
It is supposed to run in GPU mode only.

**Comment by rustycandlewick** [comment]
I see, thank you.
